src/Entity/Player.php
<?php

namespace App\Entity;

use App\Repository\PlayerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayerRepository::class)]
class Player
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $poste = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $biographie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pied = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $born_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lieu_de_naissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pays_de_naissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $taille = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    /**
     * @var Collection<int, Club>
     */
    #[ORM\ManyToMany(targetEntity: Club::class, inversedBy: 'players')]
    private Collection $club;

    public function __construct()
    {
        $this->club = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): static
    {
        $this->poste = $poste;

        return $this;
    }

    public function getBiographie(): ?string
    {
        return $this->biographie;
    }

    public function setBiographie(?string $biographie): static
    {
        $this->biographie = $biographie;

        return $this;
    }

    public function getPied(): ?string
    {
        return $this->pied;
    }

    public function setPied(?string $pied): static
    {
        $this->pied = $pied;

        return $this;
    }

    public function getBornAt(): ?\DateTimeImmutable
    {
        return $this->born_at;
    }

    public function setBornAt(?\DateTimeImmutable $born_at): static
    {
        $this->born_at = $born_at;

        return $this;
    }

    public function getLieuDeNaissance(): ?string
    {
        return $this->lieu_de_naissance;
    }

    public function setLieuDeNaissance(?string $lieu_de_naissance): static
    {
        $this->lieu_de_naissance = $lieu_de_naissance;

        return $this;
    }

    public function getPaysDeNaissance(): ?string
    {
        return $this->pays_de_naissance;
    }

    public function setPaysDeNaissance(?string $pays_de_naissance): static
    {
        $this->pays_de_naissance = $pays_de_naissance;

        return $this;
    }

    public function getTaille(): ?string
    {
        return $this->taille;
    }

    public function setTaille(?string $taille): static
    {
        $this->taille = $taille;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Club>
     */
    public function getClub(): Collection
    {
        return $this->club;
    }

    public function addClub(Club $club): static
    {
        if (!$this->club->contains($club)) {
            $this->club->add($club);
        }

        return $this;
    }

    public function removeClub(Club $club): static
    {
        $this->club->removeElement($club);

        return $this;
    }
}

src/Form/PlayerType.php
<?php

namespace App\Form;

use App\Entity\Club;
use App\Entity\Player;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlayerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('poste')
            ->add('biographie')
            ->add('pied')
            ->add('born_at', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('lieu_de_naissance')
            ->add('pays_de_naissance')
            ->add('taille')
            ->add('image')
            ->add('club', EntityType::class, [
                'class' => Club::class,
                'choice_label' => 'name',
                'multiple' => true,
                'autocomplete' => true,
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Player::class,
        ]);
    }
}

src/Controller/PlayerController.php
<?php

namespace App\Controller;

use App\Entity\Player;
use App\Form\PlayerType;
use App\Repository\PlayerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/player')]
class PlayerController extends AbstractController
{
    #[Route('/', name: 'app_player_index', methods: ['GET'])]
    public function index(PlayerRepository $playerRepository): Response
    {
        return $this->render('player/index.html.twig', [
            'players' => $playerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_player_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $player = new Player();
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($player);
            $entityManager->flush();

            return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('player/new.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_player_show', methods: ['GET'])]
    public function show(Player $player): Response
    {
        return $this->render('player/show.html.twig', [
            'player' => $player,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_player_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Player $player, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('player/edit.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_player_delete', methods: ['POST'])]
    public function delete(Request $request, Player $player, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$player->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($player);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/player/_delete_form.html.twig
<form method="post" action="{{ path('app_player_delete', {'id': player.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ player.id) }}">
    <button class="btn">Delete</button>
</form>

templates/player/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/player/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Player{% endblock %}

{% block body %}
    <h1>Edit Player</h1>

    {{ include('player/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_player_index') }}">back to list</a>

    {{ include('player/_delete_form.html.twig') }}
{% endblock %}

templates/player/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player index{% endblock %}

{% block body %}
    <h1>Player index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th></th>
                <th>Poste</th>
                <th>Biographie</th>
                <th>Pied</th>
                <th>Born_at</th>
                <th>Lieu_de_naissance</th>
                <th>Pays_de_naissance</th>
                <th>Taille</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td>{{ player.id }}</td>
                <td>{{ player.name }}</td>
                <td><img src="{{ player.image }}" alt="{{ player.name }}"></td>
                <td>{{ player.poste }}</td>
                <td>{{ player.biographie }}</td>
                <td>{{ player.pied }}</td>
                <td>{{ player.bornAt ? player.bornAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ player.lieuDeNaissance }}</td>
                <td>{{ player.paysDeNaissance }}</td>
                <td>{{ player.taille }}</td>
                <td>
                    <a href="{{ path('app_player_show', {'id': player.id}) }}">show</a>
                    <a href="{{ path('app_player_edit', {'id': player.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_player_new') }}">Create new</a>
{% endblock %}

templates/player/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Player{% endblock %}

{% block body %}
    <h1>Create new Player</h1>

    {{ include('player/_form.html.twig') }}

    <a href="{{ path('app_player_index') }}">back to list</a>
{% endblock %}

templates/player/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player{% endblock %}

{% block body %}
    <h1>Player</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ player.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ player.name }}</td>
            </tr>
            <tr>
                <th>Poste</th>
                <td>{{ player.poste }}</td>
            </tr>
            <tr>
                <th>Biographie</th>
                <td>{{ player.biographie }}</td>
            </tr>
            <tr>
                <th>Pied</th>
                <td>{{ player.pied }}</td>
            </tr>
            <tr>
                <th>Born_at</th>
                <td>{{ player.bornAt ? player.bornAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Lieu_de_naissance</th>
                <td>{{ player.lieuDeNaissance }}</td>
            </tr>
            <tr>
                <th>Pays_de_naissance</th>
                <td>{{ player.paysDeNaissance }}</td>
            </tr>
            <tr>
                <th>Taille</th>
                <td>{{ player.taille }}</td>
            </tr>
            <tr>
                <th></th>
                <td><img src="{{ player.image }}" alt="{{ player.name }}"></td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_player_index') }}">back to list</a>

    <a href="{{ path('app_player_edit', {'id': player.id}) }}">edit</a>

    {{ include('player/_delete_form.html.twig') }}
{% endblock %}